M48
; DRILL file {KiCad 8.0.4} date 2025-01-01T16:22:17-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-01T16:22:17-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X18.4Y-59.5
X19.0Y-63.9
X28.5Y-61.9
X37.5Y-60.4
T2
X23.0Y-47.0
X91.0Y-47.0
M30
